let data = {
  data: [
    { Crop: "Avocado", Variety: ["Hass", "Fuerte", "Pinkerton"] },
    {
      Crop: "Barley",
      Variety: [
        "Tumaini",
        "Bima",
        "Sabini",
        "QUENCH",
        "PEBLICAN",
        "NFC TIPPLE",
        "COCKTAIL",
        "GRACE",
        "ALICIANA",
        "Planet",
      ],
    },
    {
      Crop: "Cabbages",
      Variety: [
        "Globe Master F1 Hybrid",
        "Gloria F1 Hybrid",
        "Blue Dynasty F1",
        "Victoria F1",
        "Oxylus F1",
        "Green Coronet F1 Hybrid",
        "Riana F1 Hybrid",
        "Super Master F1",
        "Santar F1",
        "Field Winner F1 Hybrid",
        "CPI",
        "Pruktor F1 Hybrid",
        "Chihili",
        "Hero F1 (Sokoni)",
        "Ruby Perfection F1 Hybrid",
        "Red acre",
        "Copenhagen Market",
        "Glory of Enkhuizen",
        "Prize Drumhead",
        "Sugar Loaf",
        "Baraka F1",
        "Amigo F1",
      ],
    },
    { Crop: "Climbing beans", Variety: ["Flora", "Mvunikingi", "Umubano"] },
    {
      Crop: "Common Bean",
      Variety: [
        "Rose Coco (GLP 2)",
        "Chelalang",
        "Cianku",
        "EMBEAN 14 (Mwende)",
        "MN 1 (Rose Coco Madini)",
        "MN 3 (Kenya Almasi)",
        "MN 6 (Kenya Cheupe)",
        "MN 9 (Kenya Maua)",
        "KK Rose Coco - 194",
        "KK Red bean-16",
        "KKRIL05/RED 13 (KK-Red Bean 13)",
        "KKRIL05/CAL 33 (KK-Rose Coco 33)",
      ],
    },
    {
      Crop: "French beans",
      Variety: [
        "Samantha",
        "Boston",
        "Cupvert",
        "Seagull",
        "Espadia",
        "Serengeti",
        "Amy",
        "Pekara",
        "Teresa",
        "Paulista",
        "Rexas",
        "Belcampo",
        "Julia",
        "Ogandi",
        "Vernandon",
        "Sasa",
      ],
    },
    {
      Crop: "Garden Peas",
      Variety: [
        "Blue Moon ",
        "Snow peas",
        "Mammoth Melting Sugar",
        "sugar snaps Peas",
        "Dwarf Grey Sugar",
        "Oregon Sugar Pod",
        "Sugar Snap",
        "Toledo",
      ],
    },
    {
      Crop: "Linseed",
      Variety: ["Summit", "S19/21", "Raja", "Jawhar", "S19/12"],
    },
    {
      Crop: "Maize",
      Variety: [
        "FS650",
        "H611",
        "H611D",
        "H612D",
        "H613B",
        "H613D",
        "H6210",
        "H6211",
        "H6212",
        "H6213",
        "H6218",
        "H622",
        "H624",
        "H625",
        "H627",
        "H628",
        "H629",
        "KH60015A",
        "KH60016A",
        "KH60018A",
        "KH60019A",
        "KH60020A",
        "KH60023A",
        "KH60024A",
        "KS-H6220",
        "PAN 683",
        "PAN 691",
        "SC Tembo73",
        "WH 699",
        "DroughtTEGO WE4101",
        "DroughtTEGO WE4118",
        "DroughtTEGO WE4119",
        "DroughtTEGO WE5135",
        "DroughtTEGO WE5138",
        "DroughtTEGO WE5139",
        "DroughtTEGO WE5140",
        "KDH41411 (Ukamez-6)",
      ],
    },
    {
      Crop: "Nightshade",
      Variety: [
        "Abuku mnavu-1",
        "Abuku mnavu-2",
        "Abuku mnavu -3",
        "KK bigi",
        "KK Ayaro",
      ],
    },
    { Crop: "Oil Seed Rape", Variety: ["Belinda", "Hyola 50"] },
    {
      Crop: "Potato",
      Variety: [
        "Shangi",
        "Tigoni",
        "Asante",
        "Kenya Mpya",
        "Sherekea",
        "Desiree",
        "Dutch robjin",
        "Kenya Karibu",
        "Unica",
        "Purple Gold",
        "Kerr's Pink",
        "Kenya Baraka",
        "Kenya Dhamana",
        "Kenya Chaguo",
        "Kenya Mavuno",
        "Kenya Sifa",
        "Roslin Tana",
        "Roslin Bvumbwe",
        "Roslin Eburu (B53)",
        "Roslin Gucha",
        "Roslin Ruaka",
        "Pimpernel",
        "Arka",
        "Nyayo",
        "Mayan Gold",
        "Cardinal",
        "Kaumbiri",
        "Ka lucy",
        "Thima Thuti",
        "Ndera Mwana",
        "Ngure",
        "Tana Kimande",
        "Tigoni Red",
        "Komesha",
        "Meru Mugaruro",
        "Feldelslohn",
        "Lenana",
        "Wanjiku",
        "Nyota",
        "Chulu",
        "Arnova",
        "Rudolph",
        "Connect",
        "Sarpo Mira",
        "Manitou",
        "Saviola",
        "Toluca (AR97-1385)",
        "Caruso",
        "Destiny",
        "Rumba",
        "CIP 393077.159",
        "Carolus",
        "Laura",
        "Lady Amarilla",
        "Konjo",
        "El Mundo",
        "Acoustic",
        "Challenger",
        "Derby",
        "Evora",
        "Faluka",
        "Farida",
        "Jelly",
        "Kuroda",
        "Lady Terra",
        "Markies",
        "Milva",
        "Musica",
        "Panamera",
        "Rodeo",
        "Rock",
        "Royal",
        "Sagitta",
        "Sifra",
        "Taurus",
        "Voyager",
        "Zafira",
        "Zarina",
        "Ambition",
        "Lady Balfor",
        "Gemson",
        "Sorrento",
        "Reiver",
        "Cara",
      ],
    },
    {
      Crop: "Sorghum",
      Variety: [
        "BJ28",
        "Ikinyaruka",
        "E1291 (Dual Purpose)",
        "E6518 (Forage sorghum)",
        "KS-SWEET SORGH 17",
        "KS-SWEET SORGH 21",
        "EUSS10 ",
      ],
    },
    { Crop: "Spider plant", Variety: ["Spider Plant (Akeyo)"] },
    { Crop: "Sweetpotato", Variety: ["Kenspot-3", "Kenspot-4"] },
    { Crop: "Terere", Variety: ["KAT Gold", "Terere smart"] },
    {
      Crop: "Wheat",
      Variety: [
        "Kenya Kongoni",
        "Kenya Fahari",
        "Kenya Mbuni",
        "Kenya Kwale",
        "Kenya Pasa",
        "Kenya Popo",
        "Kenya Kulungu",
        "Kenya Nungu",
        "Kenya Chiriku",
        "Ngamia",
        "Kenya Heroe",
        "KS Mwamba",
        "Njoro BW1",
        "Njoro BW2",
        "KS Simba",
        "Farasi",
        "Kenya Ibis",
        "KS-Chui",
        "Kenya Robin",
        "Kenya Hawk12",
        "Kenya Wren",
        "KS-Kanga",
        "KS-Nyota",
        "Eldo Baraka",
        "Eldo Mavuno",
        "Kenya Peacock",
        "Kenya Falcon",
        "Kenya Pelican",
        "KS Wheat 04",
        "Kenya Kasuku",
        "Kenya Jacana",
        "Kenya Impala",
        "Kenya Hyrax",
      ],
    },
  ],
  message: "Data Present",
};


export {data}